$('.sysmsg').delay(4000).fadeOut('slow');$.modal.defaults={overlay:"#000000",opacity:0.5,zIndex:1001,escapeClose:false,clickClose:false,closeText:'',closeClass:'',showClose:true,modalClass:"modal",spinnerHtml:null,showSpinner:true,fadeDuration:100,fadeDelay:0.50};var buttonUp=$("#ubar");$(window).scroll(function(e){var currentScrollTop=$(window).scrollTop();if(210<=currentScrollTop){buttonUp.fadeIn(1000);}else{buttonUp.fadeOut(1000);}});$('.btn-top').click(function(e){e.preventDefault();$('html, body').animate({scrollTop:0});});function check_required_fields(){$('.required_field').removeClass('empty_field');var f=0;$('.required_field').each(function(index){if($(this).val()==''){$(this).addClass('empty_field');f++;}});setTimeout(function(){$('.required_field').removeClass('empty_field')},6000);if(f>0){return false;}else{return true;}}
$('.only_numbers').bind("change keyup input click",function(){if(this.value.match(/[^0-9]/g)){this.value=this.value.replace(/[^0-9]/g,'');}});$(function(){$('a[rel="tooltip:show"]').click(function(event){event.preventDefault();var h=$(this).attr('href');var id=$(this).attr('id');var l=$(this).next('.tooltip-wnd').length;$('.tooltip-wnd').remove();if(l==0){$.ajax({url:h,type:'POST',dataType:'html',data:{},success:function(data)
{if(data){$(data).insertAfter('#'+id);}else{window.location.href=h;}}});}});$(document).click(function(event){if($(event.target).closest('.tooltip-wnd').length==0&&$(event.target).attr('rel')!='tooltip:show'){$('.tooltip-wnd').remove();}});});$(function(){var fid=['float-block-1','float-block-2'];var topPos=fid.map(function(item,index,array){if($('#'+item).length)return $('#'+item).offset().top;});var al=$('aside.left').outerHeight();var ar=$('aside.right').outerHeight();$('aside.left').css({'height':al});$('aside.right').css({'height':ar});$(window).scroll(function(){topPos.forEach(function(item,index,array){fxb('#'+fid[index],topPos[index]);});});function fxb(fid,topPos){var top=$(document).scrollTop()+80,pip=$('footer').offset().top-20,height=$(fid).outerHeight(),ph=pip-height;if(top>topPos&&top<ph){$(fid).addClass('fixed');$(fid).removeAttr('style');$(fid).removeClass('absolute');}else if(top>=ph){$(fid).removeClass('fixed');$(fid).addClass('absolute');$(fid).css({'top':ph})}else{$(fid).removeClass('fixed');$(fid).removeClass('absolute');$(fid).removeAttr('style');}}});if($.fn.chosen!=undefined){$('.city_sel, .street_sel').chosen({no_results_text:'Ничего не найдено по запросу',allow_single_deselect:false,width:'437px'});$('.house_sel').chosen({no_results_text:'Номер дома не найден',allow_single_deselect:false,width:'150px'});$('.city_sel, .street_sel').chosen().change(function(e){var sel=$(this).attr('name'),id=$(this).val();$.ajax({url:'/house',type:'POST',dataType:'JSON',data:{'select':sel,'id':id},success:function(data)
{var html='<option value=""></option>';$.each(data,function(key,value)
{if(sel=='street'&&value['cor']!='')
{value['txt']=value['txt']+' / '+value['cor'];}
html+='<option value="'+value['val']+'">'+value['txt']+'</option>';});if(sel=='city')
{$('.street_sel').html(html).trigger("chosen:updated");}
if(sel=='street')
{$('.house_sel').html(html).trigger("chosen:updated");}}});});}
if($.fn.chosen!=undefined){var house;$(function(){$('#query-address').autocomplete({serviceUrl:$('#regid').val(),type:'post',minChars:1,maxHeight:500,zIndex:100,deferRequestBy:200,params:{task:'address_search'},noCache:true,autoSelectFirst:true,showNoSuggestionNotice:true,noSuggestionNotice:'Не найдено',onSelect:function(data){if(data.house){house=data.house;$('.btn-house-search').focus();house_search(house);}},formatResult:function(suggestion,currentValue){var reEscape=new RegExp('(\\'+['/','.','*','+','?','|','(',')','[',']','{','}','\\'].join('|\\')+')','g');var pattern='('+currentValue.replace(reEscape,'\\$1')+')';return suggestion.value.replace(new RegExp(pattern,'gi'),'<strong>$1<\/strong>');}});});function house_search(hid){if(hid){location=$('#regid').val()+'/page/'+hid;}else{location=$('#regid').val()+'/search/?q=0';}}}
function ext_house_search(){if($('.house_sel').val()){location=$('#regid').val()+'/page/'+$('.house_sel').val();}else if($('.street_sel').val()){location=$('#regid').val()+'/search/'+$('.city_sel').val()+'/'+$('.street_sel').val();}else if($('.city_sel').val()){location=$('#regid').val()+'/search/'+$('.city_sel').val();}else{location=$('#regid').val()+'/search';}}
$('.btn-clear').click(function(){$('#query-address').val('');$('#query-address').focus();$('.btn-clear').hide();});$('#query-address').keyup(function(e){if(e.keyCode==13)house_search();if($('#query-address').val()){$('.btn-clear').show();}else{$('.btn-clear').hide();}});$('.btn-ehs-close').click(function(){$('.btn-ehs-wnd').show();$('.ext-house-search').hide();});$('.btn-ehs-wnd').click(function(e){$('.btn-ehs-wnd').hide();$('.ext-house-search').slideToggle(100);});$(document).click(function(event){if($(event.target).closest('.ext-house-search').length==0&&$(event.target).attr('class')!='btn-ehs-wnd'){$('.ext-house-search').hide();$('.btn-ehs-wnd').show();}});$(function(){$('ul.tabs').on('click','li:not(.current)',function(){$(this).addClass('current').siblings().removeClass('current').parents('div.section').find('div.tab').eq($(this).index()).fadeIn(150).siblings('div.tab').hide();})});$(function(){var fb=$("#fixedbar");$(window).scroll(function(e){var cp=$(window).scrollTop();if(152<=cp){fb.addClass('fixed');}else{fb.removeClass('fixed');}});});